package fr.medab.socwokbusiness.entities;

import jakarta.persistence.*;
import static jakarta.persistence.InheritanceType.TABLE_PER_CLASS;

@MappedSuperclass
abstract class AbstractEntity {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;

    protected AbstractEntity() {
    }

    public Long getId() {
        return id;
    }

    private void setId(Long id) {
        // Id generated by the database
        this.id = id;
    }
}
